name = "lms-forum-subscription-checker"
compatibility_date = "2025-10-16"
compatibility_flags = ["nodejs_compat"]
main = "src/index.ts"

[[send_email]]
name = "EMAIL"
destination_address = "lyrion@herger.net"

[observability]
[observability.logs]
enabled = true
head_sampling_rate = 1
invocation_logs = true