name: "Read Container Registry Downloads"

on:
  workflow_dispatch:

jobs:
  get-downloads:
    runs-on: ubuntu-latest

    steps:
      - name: Set up jq
        run: sudo apt-get install -y jq

      - name: Get package downloads
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository_owner }}
        run: |
          # Define the repository and package name
          PACKAGE="lyrionmusicserver"

          # Fetch package metadata from the GitHub API
          PACKAGE_INFO=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
            "https://api.github.com/orgs/${REPO}/packages/container/${PACKAGE}")

          PACKAGE_INFO=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
            "https://api.github.com/orgs/${REPO}/packages/container/${PACKAGE}/versions")

          echo $PACKAGE_INFO | jq '.'

          PACKAGE_INFO=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
            "https://api.github.com/orgs/${REPO}/packages?package_type=container")

          echo $PACKAGE_INFO | jq '.'

          # Extract the download count
          DOWNLOAD_COUNT=$(echo "$PACKAGE_INFO" | jq '.downloads')

          if [ -z "$DOWNLOAD_COUNT" ]; then
            echo "Failed to fetch download count for package $PACKAGE"
            exit 1
          fi

          echo "The package '${PACKAGE}' has been downloaded ${DOWNLOAD_COUNT} times."